### ISSUE TITLE
Running Multiqc from nextflow but without container doesn't work

### ISSUE THREAD

**Issue by alneberg** [NationalGenomicsInfrastructure/miarka-provision#47]
The alias `multiqc` is not availble inside the nextflow bash scripts since aliases are not exported. I think this could be solved by somehow exporting the path to the local multiqc executable inside the nextflow process. It feels like this should be possible via some nextflow config file. I think this is an issue on irma as well and everybody is used to their respective workarounds, so not very urgent.

**Comment by b97pla** [comment]
This turned out not to be an issue: https://scilifelab.slack.com/archives/G4WSG4C0G/p1646467618214439
